#pragma once
#define NULL 0

enum class TileType { EASY_PATH = 0, MEDIUM_PATH, HARD_PATH, VERYHARD_PATH, WALL, SPAWN, DESTINATION };
enum class TileState { NONE, TRAVELLED = 7, EXPLORED = 8, ROVER = 9 };
enum class MessageState { NONE, NOPATH, PATHFOUND, NOSTART, NOEND, CANTLOAD, CANTSAVE, MAPSAVED, MAPLOADED, STEPDELAY, DEBUG };
